name: Running package tests and uploading code coverage

on:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint Tests
        run: npm run eslint-test
      - name: Run Prettier Tests
        run: npm run prettier-test
      - name: Run Unit Tests and Collect Coverage
        run: npm run test:ci
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
